version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    volumes:
      - mydata:/data/db
    networks:
      - testnet
  springboot-mongodb:
    build:
      context: ../../../.
      dockerfile: Dockerfile
    image: springboot:1.0.0
    container_name: "springboot"
    ports:
      - 8088:8088
    deploy:
      replicas: 3
    links:
      - mymongodb
    networks:
      - testnet
networks:
  testnet:
volumes:
  mydata:
